export const CONFIG = {
  API_URL_AUTH: process.env.EXPO_PUBLIC_API_URL_AUTH!,
  API_URL_ORDER: process.env.EXPO_PUBLIC_API_URL_ORDER!,
  API_URL_SHOP: process.env.EXPO_PUBLIC_API_URL_SHOP!,
  API_URL_CHECKOUT: process.env.EXPO_PUBLIC_API_URL_CHECKOUT!,
  API_URL_PAYMENT: process.env.EXPO_PUBLIC_API_URL_PAYMENT!
};
